#!/bin/bash
#
# Count Git commits or branches.
#
# Usage:
#
#   $ git count (c|ca|b)
#

case "$1" in
  # Commits
  c)
    # Reserved for newer versions
    git rev-list HEAD --count
    ;;

  # Number of commits by author
  ca)
    git shortlog -sn
    ;;

  # Branches
  b)
    git branch | wc -l
    ;;

  # Help
  *)
    printf "\nUsage:
      \n  $ git count (c|ca|b)\n\n"
esac