#!/bin/bash
#
# Count Git commits or branches.
#
# Usage:
#
#   $ git count [ca|b]
#

case "$1" in
  # Number of commits by author
  ca)
    git shortlog -sn
    ;;

  # Branches
  b)
    git branch | wc -l
    ;;

  # Commits
  *)
    # Reserved for newer versions
    git rev-list HEAD --count
esac
