#!/bin/bash
#
# Count git commits or branches.
#
# Usage:
#
#   $ git count (c|b)
#

case "$1" in
  c)
    # Reserved for newer versions
    git rev-list HEAD --count
    ;;
  b)
    git branch | wc -l
esac