#!/bin/bash
#
# Quicker way to credit an author on the latest commit.
#
# Usage:
#   $ git credit "NAME" EMAIL
#
# Source: https://github.com/holman/dotfiles/blob/master/bin/git-credit

git cm --amend --author "$1 <$2>" -C HEAD