#!/bin/bash
#
# Quick way to credit an author on the latest Git commit.
#
# Usage:
#
#   $ git credit "NAME" EMAIL
#
# Source: https://github.com/holman/dotfiles/blob/master/bin/git-credit

git commit --amend --author "$1 <$2>" -C HEAD
