#!/bin/bash
#
# Nuke git branch or tag.
#
# Usage:
#   $ git nuke (-b|-t) [BRANCH|TAG]

if [ $1 = -b ]
then
  git branch -D $2 && git push origin :$2
fi

if [ $1 = -t ]
then
  git tag -d $2 && git push origin :refs/tags/$2
fi