#!/bin/bash
#
# Nuke git branch or tag.
#
# Usage:
#   $ git nuke (-b|-t) (BRANCH|TAG)

case "$1" in
  -b)
    git branch -D $2 && git push origin :$2
    ;;
  -t)
    git tag -d $2 && git push origin :refs/tags/$2
esac