#!/bin/bash
#
# Make your `.gitconfig`.

echo "What is your GitHub author name?"
read -e git_name
echo "What is your GitHub author e-mail?"
read -e git_email

sed -e "s/NAME/$git_name/g" -e "s/EMAIL/$git_email/g" git/gitconfig.template \
> ~/.gitconfig