#!/bin/bash
#
# Copy 'em.
#
# Usage (run from `~/.dotfiles`):
#   $ tool/copy [DIRECTORY]

if [[ $1 == "" ]]
then
  src="*/.[^.]*"
else
  src=$1/.[^.]*
fi

for dot in $src
do
  cp $dot ~/ 2> /dev/null
done