#!/bin/bash

#
# Bash options
#

# Write history
shopt -s histappend
HISTSIZE=500
HISTFILESIZE=500
HISTCONTROL=ignoreboth
HISTTIMEFORMAT="%h %d %H:%M:%S "

# Check the window size
shopt -s checkwinsize