#!/bin/bash

#
# Bash prompt
#

# Main prompt
if [ $colors_support = true ]
then
  PS1="\[\033[1;35m\]%\[\033[00m\] \[\033[1;34m\]\w\[\033[00m\] "
fi

# Continuation prompt
PS2="\[\033[1;37m\]|\[\033[00m\] "