#!/bin/bash

#
# Bash options
#

# Write history
shopt -s histappend
HISTSIZE=500
HISTFILESIZE=1000
HISTCONTROL=ignoreboth
HISTTIMEFORMAT="%D %H:%M:%S "

# Check the window size
shopt -s checkwinsize
