#!/bin/bash

#
# Bash prompt
#

# Main prompt
PS1="$(colorize "%" purple bold) $(colorize "\w" blue bold) "

# Continuation prompt
PS2="$(colorize "|" white bold) "

# Reset prompt command
unset PROMPT_COMMAND
