#!/bin/bash

#
# Bash paths
#

# Scripts
PATH+=:~/.dotfiles/bin

# Julia (used by me)
PATH+=:~/Downloads/Packages/julia-1.5.2/bin

# Go (used by Hub)
PATH+=:/usr/lib/go/bin

# RVM secure path
export rvmsudo_secure_path=1
