#!/bin/bash

#
# Bash aliases
#

# General
if [ $(which git) ] && [ $(which hub) ]
then
  alias git=hub
fi

# Colors
if [ "$color_support" = true ]
then
  alias ls="ls --color=auto"
  alias grep="grep --color=auto"
fi

# Utilities
alias uncrlf="sed -i 's/\r$//'"

if [ $(which xclip) ]
then
  alias xcopy="xclip -sel clip"
  alias xpaste="xclip -sel clip -o"
fi
