#!/bin/bash

#
# Bash aliases
#

# General
alias git=hub
alias rdb="rethinkdb -d .rdb"

# Just if there is a color support
if [ $colors_support = true ]
then
  alias ls="ls --color=auto"
  alias grep="grep --color=auto"
fi

# Utilities
alias uncrlf="sed -i 's/\r$//'"
alias pbcopy="xclip -sel clip"
alias pbpaste="xclip -sel clip -o"