#!/bin/bash

#
# Bash aliases
#

# General
alias git=hub

if which rethinkdb > /dev/null
then
  alias rdb="rethinkdb -d .rdb"
fi

# Just with colors
if [ "$colors_support" = true ]
then
  alias ls="ls --color=auto"
  alias grep="grep --color=auto"
fi

# Utilities
alias uncrlf="sed -i 's/\r$//'"

if which xclip > /dev/null
then
  alias pbcopy="xclip -sel clip"
  alias pbpaste="xclip -sel clip -o"
fi